// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV_RC9Zlyd6xvQYsUcNZoxvqPRSE8J9IY',
    appId: '1:162142886384:web:8b4e3d0cb6cc7fac79a535',
    messagingSenderId: '162142886384',
    projectId: 'nto-twitclone',
    authDomain: 'nto-twitclone.firebaseapp.com',
    storageBucket: 'nto-twitclone.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmU057Iv_rABIb8Rhx_pv0MlPqlUeG1Y4',
    appId: '1:162142886384:android:ab284371ad65745e79a535',
    messagingSenderId: '162142886384',
    projectId: 'nto-twitclone',
    storageBucket: 'nto-twitclone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbGCYC1ytl1H4XE1IZXd5O1X66q0NrYCc',
    appId: '1:162142886384:ios:83e1c5e616da5c9179a535',
    messagingSenderId: '162142886384',
    projectId: 'nto-twitclone',
    storageBucket: 'nto-twitclone.appspot.com',
    iosBundleId: 'com.example.finalPrj',
  );
}
